version: 2.1
jobs:
  build:
    macos:
      xcode: "11.3.1"

    steps:
      - checkout

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_WORKSPACE: IGListKit.xcworkspace
            SCAN_DEVICE: iPhone 11
            SCAN_SCHEME: IGListKit

      - store_test_results:
          path: test_output
 
      - store_artifacts:
          path: test_output
      
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs